[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.111.3"

# [[redirects]]
#  from = "/*"
#  to = "/en/404.html"
#  status = 404

# [[redirects]]
#  from = "/en/*"
#  to = "/en/404.html"
#  status = 404

# [[redirects]]
#  from = "/fr/*"
#  to = "/fr/404.html"
#  status = 404

# This is a starter template for Netlify builds. See the following links for more:
# https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
# https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/
