name: Extract docs from zip file

on:
  push:
    branches: [ master ]
    paths:
    - '**.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - name: Create local changes
      run: |
        rm -r static/docs
        unzip 38960-Coveo_Test-html5_-Github_Coveo.zip
        rm *.zip
        mv 38960-Coveo_Test-html5/out static/docs
        rm -r 38960-Coveo_Test-html5
    - name: Commit files
      run: |
        git config --local user.email "github-actions@users.noreply.github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -a -m "Add changes"
    - name: Push changes
      run: git push origin master
